#设置服务端口
server:
  port: 9902
spring:
  cloud:
    stream:
      kafka:
        binder:
          #可通过配置group的方式来配置消费服务启动之前为消费的消息,不配置则之前消息无法消费(丢失)
          brokers: localhost:9092
      bindings:
        #自定义输入通道名称
        input_msg:
          #加入消费组(同一个组的服务只能有一个能消费到消息)
          group: Group-1
          #设置自定义输入通道的消费的主题
          destination: topic-1
        #Stream内置的输入通道名称
        input:
          #设置内置输入通道的消费的主题
          destination: topic-2
          
